Repository Team-Soup-Soup/Soup-FE, pull requests merged in 2025-02, with the labels that each got.

#3 feat: custom CSS 설정
  .prettierrc
  apps/land/app/globals.css
  apps/land/app/layout.tsx
  apps/land/tailwind.config.ts
  apps/web/.eslintrc.cjs
  apps/web/src/global.css
  apps/web/src/index.css
  apps/web/src/main.tsx
Labels: ✨ Feature

#4 feat: 랜딩 페이지 개발
  apps/land/app/globals.css
  apps/land/app/layout.tsx
  apps/land/app/page.tsx
  apps/land/package.json
  apps/land/public/favicon/favicon.ico
  apps/land/public/images/land-header.png
  apps/land/public/images/land-slide-1.png
  apps/land/public/images/land-slide-2.png
  apps/land/public/images/land-slide-3.png
  apps/land/public/images/land-slide-4.png
  apps/land/public/images/people-1.png
  apps/land/public/images/people-2.png
  apps/land/public/images/people-3.png
  apps/land/public/images/soup.png
  apps/land/src/app/globals.css
  apps/land/src/app/layout.tsx
  apps/land/src/app/page.tsx
  apps/land/src/assets/fonts/Pretendard-Bold.otf
  apps/land/src/assets/fonts/Pretendard-Medium.otf
  apps/land/src/assets/fonts/Pretendard-SemiBold.otf
  apps/land/src/shared/utils/index.ts
  apps/land/src/shared/utils/string.tsx
  apps/land/src/widgets/home/model/constants/home.ts
  apps/land/src/widgets/home/model/constants/index.ts
  apps/land/src/widgets/home/model/index.ts
  apps/land/src/widgets/home/ui/FeatureCarousel.tsx
  apps/land/src/widgets/home/ui/HomeContainer.tsx
  apps/land/src/widgets/home/ui/OpinionUnit.tsx
  apps/land/src/widgets/home/ui/index.ts
  apps/land/src/widgets/menu/ui/Footer.tsx
  apps/land/src/widgets/menu/ui/Nav.tsx
  apps/land/src/widgets/menu/ui/index.ts
  apps/land/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature

#5 feat: 디자인 시스템 구축
  .gitignore
  apps/web/src/globals.css
  apps/web/src/main.tsx
  packages/design-system/.storybook/main.ts
  packages/design-system/.storybook/preview.ts
  packages/design-system/package.json
  packages/design-system/postcss.config.ts
  packages/design-system/public/chevron-left.svg
  packages/design-system/public/chevron-right.svg
  packages/design-system/public/chevrons-left.svg
  packages/design-system/public/chevrons-right.svg
  packages/design-system/public/search.svg
  packages/design-system/src/Button/Button.stories.tsx
  packages/design-system/src/Button/Button.styles.ts
  packages/design-system/src/Button/Button.tsx
  packages/design-system/src/Button/Button.types.ts
  packages/design-system/src/Button/index.ts
  packages/design-system/src/Checkbox/Checkbox.stories.tsx
  packages/design-system/src/Checkbox/Checkbox.tsx
  packages/design-system/src/Checkbox/index.ts
  packages/design-system/src/Header/Header.stories.tsx
  packages/design-system/src/Header/Header.tsx
  packages/design-system/src/Header/index.ts
  packages/design-system/src/Input/Input.stories.tsx
  packages/design-system/src/Input/Input.tsx
  packages/design-system/src/Input/index.ts
  packages/design-system/src/Pagination/Pagination.stories.tsx
  packages/design-system/src/Pagination/Pagination.tsx
  packages/design-system/src/Pagination/index.ts
  packages/design-system/src/Radio/Radio.stories.tsx
  packages/design-system/src/Radio/Radio.tsx
  packages/design-system/src/Radio/index.ts
  packages/design-system/src/Toggle/Toggle.stories.tsx
  packages/design-system/src/Toggle/Toggle.tsx
  packages/design-system/src/Toggle/index.ts
  packages/design-system/src/constants.ts
  packages/design-system/src/globals.css
  packages/design-system/src/stories/readme.mdx
  packages/design-system/src/types.ts
  packages/design-system/tailwind.config.js
  packages/design-system/tsconfig.json
  packages/design-system/vite.config.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/string.ts
  packages/utils/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature

#8 refactor: 유틸 패키지 `cn` 적용
  apps/land/package.json
  apps/land/src/shared/utils/string.tsx
  apps/land/src/widgets/home/ui/OpinionUnit.tsx
  pnpm-lock.yaml
Labels: 👓 Refactor

#12 feat: 로그인, 회원가입 페이지 레이아웃 생성
  apps/web/README.md
  apps/web/index.html
  apps/web/package.json
  apps/web/public/favicon/favicon.ico
  apps/web/public/vite.svg
  apps/web/src/App.tsx
  apps/web/src/app/globals.css
  apps/web/src/app/layouts/AuthLayout.tsx
  apps/web/src/app/layouts/index.ts
  apps/web/src/app/main.tsx
  apps/web/src/app/routers/AuthRouter.tsx
  apps/web/src/app/routers/index.ts
  apps/web/src/app/routes/AuthRoutes.tsx
  apps/web/src/app/routes/ProtectedRoutes.tsx
  apps/web/src/app/routes/index.ts
  apps/web/src/app/vite-env.d.ts
  apps/web/src/assets/images/login-signup-image.png
  apps/web/src/main.tsx
  apps/web/src/pages/home/ui/HomePage.tsx
  apps/web/src/pages/home/ui/index.ts
  apps/web/src/pages/login/ui/LoginPage.tsx
  apps/web/src/pages/login/ui/index.ts
  apps/web/src/shared/constants/index.ts
  apps/web/src/shared/constants/path.ts
  apps/web/src/shared/hooks/index.ts
  apps/web/src/shared/hooks/useLoginStatus.ts
  apps/web/tsconfig.json
  apps/web/vite.config.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#14 fix: design-system import 에러 수정
  apps/web/package.json
  packages/design-system/.storybook/main.ts
  packages/design-system/package.json
  packages/design-system/postcss.config.ts
  packages/design-system/src/globals.css
  packages/design-system/src/index.ts
  packages/design-system/storybook-static/favicon.svg
  packages/design-system/storybook-static/index.html
  packages/design-system/storybook-static/index.json
  packages/design-system/storybook-static/nunito-sans-bold-italic.woff2
  packages/design-system/storybook-static/nunito-sans-bold.woff2
  packages/design-system/storybook-static/nunito-sans-italic.woff2
  packages/design-system/storybook-static/nunito-sans-regular.woff2
  packages/design-system/storybook-static/project.json
  packages/design-system/storybook-static/sb-addons/chromatic-com-storybook-11/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/chromatic-com-storybook-11/manager-bundle.js.LEGAL.txt
  packages/design-system/storybook-static/sb-addons/essentials-actions-4/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-backgrounds-6/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-controls-3/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-docs-5/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-measure-9/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-outline-10/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-toolbars-8/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/essentials-viewport-7/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/interactions-12/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/links-2/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/onboarding-1/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/pseudo-states-13/manager-bundle.js
  packages/design-system/storybook-static/sb-addons/storybook-core-core-server-presets-0/common-manager-bundle.js
  packages/design-system/storybook-static/sb-common-assets/favicon.svg
  packages/design-system/storybook-static/sb-common-assets/nunito-sans-bold-italic.woff2
  packages/design-system/storybook-static/sb-common-assets/nunito-sans-bold.woff2
  packages/design-system/storybook-static/sb-common-assets/nunito-sans-italic.woff2
  packages/design-system/storybook-static/sb-common-assets/nunito-sans-regular.woff2
  packages/design-system/storybook-static/sb-manager/globals-module-info.js
  packages/design-system/storybook-static/sb-manager/globals-runtime.js
  packages/design-system/storybook-static/sb-manager/globals.js
  packages/design-system/storybook-static/sb-manager/runtime.js
  packages/design-system/tailwind.config.js
  packages/design-system/tsconfig.json
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
Labels: 🛠️ Fix

#15 feat: 로그인, 회원가입 UI 구현
  apps/web/src/app/layouts/AuthLayout.tsx
  apps/web/src/app/main.tsx
  apps/web/src/app/routes/AuthRoutes.tsx
  apps/web/src/assets/icons/chevron-left.svg
  apps/web/src/assets/icons/kakao.svg
  apps/web/src/features/login/ui/LoginForm.tsx
  apps/web/src/features/login/ui/LoginOption.tsx
  apps/web/src/features/login/ui/index.ts
  apps/web/src/features/signup/model/constants/form.ts
  apps/web/src/features/signup/model/constants/index.ts
  apps/web/src/features/signup/model/index.ts
  apps/web/src/features/signup/types/form.ts
  apps/web/src/features/signup/types/index.ts
  apps/web/src/features/signup/ui/SignupForm.tsx
  apps/web/src/features/signup/ui/index.ts
  apps/web/src/pages/login/ui/LoginPage.tsx
  apps/web/src/pages/signup/ui/SignupPage.tsx
  apps/web/src/pages/signup/ui/index.ts
  apps/web/src/widgets/login/ui/LoginContainer.tsx
  apps/web/src/widgets/login/ui/SignupLink.tsx
  apps/web/src/widgets/login/ui/SocialLogin.tsx
  apps/web/src/widgets/login/ui/index.ts
  packages/config/globals.css
  packages/config/package.json
  packages/design-system/.storybook/preview.ts
  packages/design-system/src/Button/Button.styles.ts
  packages/design-system/src/Button/Button.tsx
  packages/design-system/src/Checkbox/Checkbox.tsx
  packages/design-system/src/Input/Input.tsx
  packages/design-system/src/globals.css
  packages/design-system/src/index.ts
  packages/design-system/tailwind.config.js
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
  turbo.json
Labels: ✨ Feature

#17 feat: 로그인, 회원가입 유효성 검사 구현
  apps/web/package.json
  apps/web/src/app/routes/AuthRoutes.tsx
  apps/web/src/features/find-account/model/index.ts
  apps/web/src/features/find-account/model/utils/handleFormSubmit.ts
  apps/web/src/features/find-account/model/utils/index.ts
  apps/web/src/features/find-account/types/index.ts
  apps/web/src/features/find-account/types/user.ts
  apps/web/src/features/find-account/ui/FindAccountForm.tsx
  apps/web/src/features/find-account/ui/index.ts
  apps/web/src/features/login/model/hooks/index.ts
  apps/web/src/features/login/model/hooks/useSubmit.ts
  apps/web/src/features/login/model/index.ts
  apps/web/src/features/login/types/index.ts
  apps/web/src/features/login/types/user.ts
  apps/web/src/features/login/ui/LoginForm.tsx
  apps/web/src/features/login/ui/LoginOption.tsx
  apps/web/src/features/signup/model/constants/index.ts
  apps/web/src/features/signup/model/constants/state.ts
  apps/web/src/features/signup/model/constants/user.ts
  apps/web/src/features/signup/model/index.ts
  apps/web/src/features/signup/model/utils/checkValidation.ts
  apps/web/src/features/signup/model/utils/handleFormSubmit.ts
  apps/web/src/features/signup/model/utils/index.ts
  apps/web/src/features/signup/types/form.ts
  apps/web/src/features/signup/types/index.ts
  apps/web/src/features/signup/types/state.ts
  apps/web/src/features/signup/types/user.ts
  apps/web/src/features/signup/ui/EmailVerification.tsx
  apps/web/src/features/signup/ui/FormInput.tsx
  apps/web/src/features/signup/ui/FormSubmit.tsx
  apps/web/src/features/signup/ui/FormUnit.tsx
  apps/web/src/features/signup/ui/FormUnitWithButton.tsx
  apps/web/src/features/signup/ui/SignupForm.tsx
  apps/web/src/features/signup/ui/index.ts
  apps/web/src/pages/find-account/ui/FindAccountPage.tsx
  apps/web/src/pages/find-account/ui/index.ts
  apps/web/src/pages/signup/ui/SignupPage.tsx
  apps/web/src/shared/constants/path.ts
  apps/web/src/shared/ui/AuthHeader.tsx
  apps/web/src/shared/ui/index.ts
  apps/web/src/widgets/login/ui/SocialLogin.tsx
  packages/config/globals.css
  pnpm-lock.yaml
Labels: ✨ Feature, Ⓦ Web

#16 feat: Modal 셋팅, 사이드바 ui 구현
  apps/web/package.json
  apps/web/public/icons/bell_activate.svg
  apps/web/public/icons/project.svg
  apps/web/public/icons/project_plus.svg
  apps/web/public/images/empty_project.webp
  apps/web/public/images/user_profile.webp
  apps/web/src/app/layouts/HomeLayout.tsx
  apps/web/src/app/layouts/index.ts
  apps/web/src/app/main.tsx
  apps/web/src/app/routes/HomeRoutes.tsx
  apps/web/src/app/routes/index.ts
  apps/web/src/mocks/alarm.json
  apps/web/src/mocks/index.ts
  apps/web/src/mocks/project.json
  apps/web/src/pages/home/ui/HomePage.tsx
  apps/web/src/shared/atoms/index.ts
  apps/web/src/shared/atoms/modal.ts
  apps/web/src/shared/atoms/project.ts
  apps/web/src/shared/constants/index.ts
  apps/web/src/shared/constants/modal.ts
  apps/web/src/shared/constants/state.ts
  apps/web/src/shared/hooks/index.ts
  apps/web/src/shared/hooks/useModal.ts
  apps/web/src/shared/hooks/useProject.ts
  apps/web/src/shared/types/index.ts
  apps/web/src/shared/types/modal.ts
  apps/web/src/shared/ui/IconButton.tsx
  apps/web/src/shared/ui/Modal.tsx
  apps/web/src/shared/ui/Profile.tsx
  apps/web/src/shared/ui/index.ts
  apps/web/src/shared/utils/Providers.tsx
  apps/web/src/shared/utils/index.ts
  apps/web/src/widgets/home/ui/HomeContainer.tsx
  apps/web/src/widgets/home/ui/index.ts
  apps/web/src/widgets/menu/ui/Sidebar.tsx
  apps/web/src/widgets/menu/ui/index.ts
  apps/web/src/widgets/modal/ui/AlarmModal.tsx
  apps/web/src/widgets/modal/ui/CreateProjectModal.tsx
  apps/web/src/widgets/modal/ui/LogoutModal.tsx
  apps/web/src/widgets/modal/ui/SettingModal.tsx
  apps/web/src/widgets/modal/ui/index.ts
  apps/web/src/widgets/modal/ui/setting/ProfileSetting.tsx
  apps/web/src/widgets/modal/ui/setting/SecuritySetting.tsx
  apps/web/src/widgets/modal/ui/setting/ToggleController.tsx
  apps/web/src/widgets/modal/ui/setting/index.ts
  packages/config/globals.css
  packages/design-system/package.json
  packages/design-system/src/Button/Button.styles.ts
  packages/design-system/src/Input/Input.tsx
  packages/design-system/src/Toggle/Toggle.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, Ⓦ Web
